### ISSUE TITLE
UnsupervisedFeedbackHandler - 500 error/NullPointerException (Solr 6.3.0)

### ISSUE THREAD

**Issue by jstol** [DiceTechJobs/RelevancyFeedback#2]
Hi Simon,

I recently watched a video of the "Personalized Search and Job Recommendations" talk you did at Revolution 2017 and decided to try out the unsupervised feedback plugin. I seem to be running into some issues, though.

I've configured an `UnsupervisedFeedbackHandler` based on the example config you have (modified as needed), but the handler is throwing a `500` error.

I have a fresh Solr 6.3 instance with some dummy data (just `id` and `text` fields). Any insight into what could be going on would be greatly appreciated.

See stack trace below:

```
java.lang.NullPointerException
	at org.apache.solr.util.SolrPluginUtils.calculateMinShouldMatch(SolrPluginUtils.java:690)
	at org.apache.solr.util.SolrPluginUtils.setMinShouldMatch(SolrPluginUtils.java:654)
	at org.apache.solr.util.SolrPluginUtils.setMinShouldMatch(SolrPluginUtils.java:661)
	at org.dice.solrenhancements.relevancyfeedback.RFQuery.getOrQuery(RFQuery.java:51)
	at org.dice.solrenhancements.unsupervisedfeedback.UnsupervisedFeedbackHelper.expandQueryAndReExecute(UnsupervisedFeedbackHelper.java:119)
	at org.dice.solrenhancements.unsupervisedfeedback.UnsupervisedFeedbackHandler.expandQueryAndReExecute(UnsupervisedFeedbackHandler.java:234)
	at org.dice.solrenhancements.unsupervisedfeedback.UnsupervisedFeedbackHandler.handleRequestBody(UnsupervisedFeedbackHandler.java:132)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:153)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2213)
	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:654)
	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:460)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:303)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1092)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:518)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:246)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:156)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

Thanks!

**Comment by simonhughes22** [comment]
@jstol how are you call it and how is it configured? Are you using the 6.30 branch? It's quite easy to attach solr to the debugger if needed to debug this sort of issue. I can't say from just the stack trace what's going on. Are you passing in the mm parameter? If so, make sure you are using the correct format, and try removing it and allowing it to use the default. If you are not specifying it, try specifying it. But knowing your solr version, your config and providing me an example of how it's being called would help me troubleshoot it.

**Comment by jstol** [comment]
@simonhughes22 thanks for getting back to me. I was using master (based on the part of the README that says "`Solr 6.3 (see branch) also master`"), but I'll try out the `Solr.6.3.0` branch to see if I get the same issues.

My configuration was basically the same as in your example, but for the initial retrieval step I configured `defType` to  `dismax` by default and only set a `df` of `"text"` - no other default settings.

ie. the section with:
```
<!-- Regular query configuration -->
<str  name="defType">edismax</str>
<str  name="df">title</str>
<str  name="qf">title^1.5   skills^1.25 description^1.1</str>
<str  name="pf2">title^3.0  skills^2.5  description^1.5</str>
<str  name="mm">1</str>
<str  name="q.op">OR</str>
```

became something similar to:

```
<!-- Regular query configuration -->
<str  name="defType">dismax</str>
<str  name="df">title</str>
```

(And of course I changed field names as needed). Not sure if the handler was designed to assume that a default `mm` parameter is specified within this section, but I seemed to get an exception without it.

I ended up attaching the debugger and stepping through the code to figure out where I was having my issues. I submitted some changes in a pull request, which you can see here: https://github.com/DiceTechJobs/RelevancyFeedback/pull/3. It seems like a default value for `mm` isn't set within `UnsupervisedFeedbackHelper`, which was causing it to throw an Exception. Not sure if I modified it to handle it properly, though.

Thanks!

**Comment by simonhughes22** [comment]
Committed PR. Should address this.
